name: Feature Request
description: Suggest an improvement or new feature
labels: ["enhancement"]
body:
  - type: textarea
    id: description
    attributes:
      label: What would you like?
      description: Describe the feature or improvement.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Context
      description: Why is this useful? What problem does it solve?
    validations:
      required: false
